---
# tasks file for tomcat

- name: "create tomcat_as group"
  group: name={{tomcat_group}} state=present
- name: "create tomcat_as user"
  user: name={{tomcat_user}} group={{tomcat_group}} home={{tomcat_home}} createhome=no state=present
- name: tomcat archive exists
  stat: path=/tmp/apache-tomcat-{{tomcat_version}}.tar.gz
  register: archive_exists
- name: "download tomcat {{tomcat_version}}"
  get_url: url={{tomcat_url}} dest=/tmp/
  when: archive_exists.stat.exists == false
- name: "extract tomcat"
  unarchive: src=/tmp/apache-tomcat-{{tomcat_version}}.tar.gz dest=/tmp remote_src=yes
- name: "copy tomcat"
  shell: 'mkdir -p /opt/tomcat/{{tomcat_version}} && cp -r /tmp/apache-tomcat-{{tomcat_version}}/* /opt/tomcat/{{tomcat_version}}/'
- name: "set tomcat user ownership"
  file: path={{tomcat_home}} recurse=yes state=directory owner={{tomcat_user}} group={{tomcat_group}}
- name: "copy tomcat conf"
  template: src=server.xml dest={{tomcat_home}}/conf/server.xml
- name: "copy tomcat-users conf"
  template: src=tomcat-users.xml dest={{tomcat_home}}/conf/tomcat-users.xml
- name: "copy manager app conf"
  template: src=context.xml dest={{tomcat_home}}/webapps/manager/META-INF/context.xml
- name: "tomcat init script creation"
  template: src=tomcat dest=/etc/init.d/tomcat mode=0755
  notify: restart tomcat
- name: "enable tomcat service"
  shell: chkconfig --add tomcat
- name: ensure tomcat is started
  service: name=tomcat enabled=yes state=started
- name: wait for tomcat to start
  wait_for: port={{tomcat_http_port}}
