- name: provision VM
  hosts: localhost
  connection: local
  tasks:
  - name: vagrant vm provision
    vagrant: path=../resources/virtualbox/ state=started
    register: output
  - name: add host info
    lineinfile:
      dest: ../inventory/dev
      insertafter: '^\[dev\]'
      line: "name={{ output.vm_ip }} hostname={{ output.vm_ip }} ansible_ssh_host={{ output.vm_ip }} ansible_ssh_port={{ output.vm_port }} ansible_ssh_private_key_file={{ output.ssh_key_file }} ansible_user={{ output.username }}"
      state: present
    when: output.state == "running"