---
# tasks file for nginx

- name: nginx is installed
  yum: name=nginx state=present
  become: yes
  become_user: root
  no_log: yes
- name: copy nginx config
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  become: yes
  become_user: root
  notify: restart nginx
- name: ensure nginx is started
  service: name=nginx enabled=yes state=started
  become: yes
  become_user: root
- name: wait for nginx to start
  wait_for: port={{nginx_port}}

